### ISSUE TITLE
Getting started document with cd and cd-crc

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#1]
document your steps to setup an environment

**Comment by martinpovolny** [comment]
* Setup CRC https://developers.redhat.com/products/codeready-containers/overview
* (optional?) add more memory to CRC
 * Get `kustomize` and KSOPS using steps in https://aicoe.github.io/aicoe-cd/manage_your_app_secrets/
      * If hit with 
``` unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp ```,
fix it with https://github.com/viaduct-ai/kustomize-sops/issues/60
 * Fork https://github.com/operate-first/continuous-deployment
 * Import GPG key that is used by kustomize to encrypt the secrets. (Correct command here: https://github.com/operate-first/continuous-deployment/pull/21/files)
 * Proceed with https://aicoe.github.io/aicoe-cd/setup_argocd_dev_environment/

**Comment by durandom** [comment]
@martinpovolny I think you started documenting this somewhere else? And did we want to add the documentation into https://github.com/operate-first/continuous-deployment/tree/master/docs/downstream ?

**Comment by martinpovolny** [comment]
@durandom : yes, I started by forking the repo. But nvm, I've created a PR similar to what @tumido did. I think we should try to be consistent.

https://github.com/operate-first/continuous-deployment/pull/33
