### ISSUE TITLE
Create Site Footer

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#106]
Can we create a footer for the site, something similar to the footer in the patternfly[website](https://www.patternfly.org/v4/contribute/about), or [opendatahub.io](http://opendatahub.io/).

Something like [mockup](https://github.com/operate-first/operate-first.github.io/issues/95#issuecomment-726875525)?

**Comment by durandom** [comment]
@oindrillac we now have a footer in https://github.com/operate-first/operate-first.github.io/blob/master/src/components/Layout/Layout.js#L23-L29 

Could you create a PR to add some more content to it. Not sure what though 😆

**Comment by oindrillac** [comment]
Add some text below the Contribute
Red Hat initiative add some html
logo by this person - source of logo, reference them
