### ISSUE TITLE
preview PR

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#11]
Travis can also build PRs. Is there a way to preview the output of a PR build? 
Maybe there's a free service to serve HTML pages? How are others in the gatsby community solving this?

Maybe
https://www.linode.com/docs/websites/static-sites/install-gatsbyjs/#preview-your-site-with-netlify

this is probably a bit tricky.

**Comment by cfchase** [comment]
I'll have to look into this a bit deeper.

For now, contributors can use their own GitHub pages site to preview changes and they could link it in their PR to show reviewers.  Unfortunately, it's just a single site per contributor, not for each PR.

Maybe this won't solve the problem, but it's at least it's easy and useful. https://github.com/operate-first/operate-first.github.io/pull/20

**Comment by tumido** [comment]
I think we can push it a bit forward with `gh-pages` tweaks. See #21

I've made `gh-pages` to deploy multiple instances of the repo into the same`gh-pages` branch in the fork, so each contributor can now host multiple instances of the pages.

**Comment by cfchase** [comment]
I like it!  My only comment was we can offer both the preview fork and preview pr tasks separately.

**Comment by cfchase** [comment]
If this is not enough, we can probably come up with a system where a separate preview site is created, a CI task downloads and builds PRs, and pushes each PR the same way you're deploying them in subdirectories.  We probably wouldn't want to do them in this org though cause they'd show up underneath our main site.
