### ISSUE TITLE
Question regarding image location for publishing doc

### ISSUE THREAD

**Issue by SankBad** [operate-first/operate-first.github.io-old#110]
I am trying to publish a project [doc](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/docs/publish/failure-type-classification-with-the-testgrid-data-project-doc.md). 
Currently, an Image in the doc exists in another folder. when I am trying to publish a doc, it's not rendering the image. 

Should images exist in the same folder as a doc? or relative path is fine and I am missing something?

You can preview the website over [here](https://sankbad.github.io/operate-first.github.io/aici/failure-type-classification-with-the-testgrid-data-project-doc)

**Comment by oindrillac** [comment]
@SankBad I tried testing from your [fork](https://github.com/SankBad/operate-first.github.io.git) and I am able to see the image in the blog. 
![image](https://user-images.githubusercontent.com/32435206/99799910-79998d00-2b01-11eb-9b33-3853a3de364d.png)

Let me know if its still an issue

**Comment by SankBad** [comment]
Fresh clone worked. :bow:
