### ISSUE TITLE
Resize images in markdown posts

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#111]
@cfchase is there a way to resize images within markdown blog posts?

Tried putting html in markdown for referencing images like follows, and adjusting the width and height
 
`<img src="../assets/images/annotated_testgrid.png" width="3000" height="1000"/>`

but that does not seem to work. Do you have any ideas?

**Comment by cfchase** [comment]
The global config needs to be changed in the [gatsby-config.js](https://github.com/operate-first/operate-first.github.io/blob/master/gatsby-config.js#L29).  Change the `maxWidth` of `gatsby-remark-images` `options` to be whatever you think  you'll need.  In the following I picked 1600px
```javascript
{
  resolve: `gatsby-remark-images`,
  options: {
    maxWidth: 1600,
  },
},
```
Be careful, as this will change everyone's images across the site.

and in your MDX files
```html
<div class="my-image2" style="width:200px;">
    <img class="contained-image" src="./approach.png"/>
</div>
```


__Explanation__:
This was surprisingly less straightforward than I hoped for.  With Gatsby/MDX the answer always seems to be custom React components or html.  In this case the `gatsby-remark-images` plugin is generating the component for images even if you use an `<img/>` tag, so using a styled container seems to be the most straightforward solution.

If you do this across many places across the site, you can make a css file and include it directly in your markdown 
```javascript
import "./my-blogs-custom.css";
```
or add some classes to the `Doc.scss` template everyone can use in their image containers. 
```css
.my-image-container-large {
  width: 500px;
}
```

You can also make a custom component to use in your MDX files
```jsx
export const ImgContainer = ({ width, height, center, etc }) => {
}
```

**Comment by oindrillac** [comment]
Thanks this is very helpful @cfchase :pray:
