### ISSUE TITLE
Re-Org of site navigation

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#116]
The left hand navigation is getting crowded. I propose a horizontal navigation and a vertical navigation changing, depending on the top navigation. Similar to https://kubernetes.io/ 
See also the [Patternfly Design Guidelines](https://www.patternfly.org/v4/components/navigation/design-guidelines)

### Horizontal Top Navigation
* Logo: Home Page
* Data Science Projects
* Users
* Operators
* Operate First [ generic content, not related to any specific implementation ]

### Vertical Navigation 

This will remain a 2 level navigation. The topmost bulletpoint is the horizontal nav

* Logo: Home Page
	* Operate First for Open Data Hub
	* Getting Started / Home
* Data Science Projects
	* Projects Overview
	* DS Workflow
	* AI for CI
	* Categorical Encoding
	* ...
* Users
	* Getting Access to ODH
	* Components
	* Help
*  Operators
	* Installation
		* CRC
		* Quicklab
		* MOC
	* MOC
		* Getting Access
		* Hardware configuration
		* Status Dashboards
* Operate First
	* Architecture Decision Records
              * Use Markdown Architectural Decision Records
	* Continuous Integration 
	* Continuous Delivery
	* SRE

cc @goern @cfchase @oindrillac

**Comment by goern** [comment]
Hmm, it feels like the "Operate First" should be first on the left hand. And what is  "operators" is it creating a kubernetes operator or is is a section "for Operators" ?

**Comment by durandom** [comment]
![image](https://user-images.githubusercontent.com/161888/99951245-0a7c9c80-2d7e-11eb-81aa-c6d466a19de8.png)

**Comment by durandom** [comment]
It's structured by audience:

* Data Science (for the DS folks that want to learn about DS on ODH)
* Users (all Users for ODH, much like "how do I get access, where to report issues, how do I create an s2i image)
* Operators (folks that operate the thing, ODH, OCP, etc)
* Blueprints (generic stuff, that can be applied to other initiatives as well)

**Comment by durandom** [comment]
See preview here: http://durandom.de/operate-first.github.io/top_nav/

**Comment by oindrillac** [comment]
@durandom +1 for the vertical and horizontal nav. This will allow us to bring some good structure to our documents.
Also I like the broad sections and that they're ordered from a "user" standpoint.

Where do you see access documents to deployed odh components - like [JupyterHub on MOC ](https://www.operate-first.cloud/odh-moc-user/jupyterhub)going? 
Under Users > Components or under Operators > MOC ?

I would assume these deployed components should be readily accessible to Users.
