### ISSUE TITLE
burger menu does not open

### ISSUE THREAD

**Issue by goern** [operate-first/operate-first.github.io-old#125]
if I load/reload https://www.operate-first.cloud/ the left-hand side menu is invisible, clicking on the burger does not show it, if I click on "data science" if do see the left-hand navigation.

/kind bug
/priority critical-urgent

**Comment by oindrillac** [comment]
I thought that's how @durandom meant it to be? Since right now we do not have any _Home_ category documents, there seems no need for a left hand menu. As one selects a category out of the 4, from the top nav, only then a left hand menu item becomes visible

**Comment by goern** [comment]
ah, ok. confusing... ;) as you can see, it felt like a bug

**Comment by durandom** [comment]
yep, if there's no lefthand nav, the 🍔  should be gone
