### ISSUE TITLE
handle relative links to index files

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#138]
Relative links to index files such as for `gpg keys` under the `Install Argo CD on your cluster` in this [doc](https://www.operate-first.cloud/operators/continuous-deployment/docs/downstream/quicklab.md) do not work since the link points to https://www.operate-first.cloud/operators/continuous-deployment/README.md#gpg-key-access should instead point to https://www.operate-first.cloud/operators/continuous-deployment/#gpg-key-access.

How can we handle cases like this? Should the files be renamed or the links be modified?

cc: @durandom

**Comment by durandom** [comment]
I'm inclined to revert https://github.com/operate-first/operate-first.github.io/blob/ef4c0469b7238d3624a91e0f5fd6f7442237fd0f/gatsby-node.js#L31 

We could come up with sophisticated solutions like  redirects or rewrites, but that's too error prone IMHO.

@tumido @oindrillac thoughts?

**Comment by durandom** [comment]
Actually that breaks how people link on GH to a directory. I'll just create a second URL, which introduces duplicated content, but it's easier to implement than a redirect..

**Comment by tumido** [comment]
What about we just mutate the relative links in the processed markdown files to strip the `README.md` away? We don't need to solve this on the router level, if we can fix the content on the fly... 

Something like this: https://github.com/gatsbyjs/gatsby/issues/15868#issuecomment-512859053

**Comment by durandom** [comment]
That's too complicated for my skills. I've just re-added `README.md` links. https://github.com/operate-first/operate-first.github.io/pull/159
