### ISSUE TITLE
line break tags in markdown breaks build

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#141]
Build from #140 errored out because of the markdown line break tags in https://github.com/operate-first/continuous-delivery/blob/master/docs/setup_cd_pipeline.md

Log:
```
ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

unknown: Expected corresponding JSX closing tag for <br> (14:74)

  12 | <li parentName="ul">
  13 | <p parentName="li">{`AICoE-CI is available as `}<a parentName="p" {...{"href":"https://github.com/apps/aicoe-ci"}}>{`github application`}</a>{`.`}<br>{`
> 14 | Install and configure the app on your GitHub Organization or Repository.`}</p>
     |                                                                           ^
  15 | </li>
  16 | <li parentName="ul">
  17 | <p parentName="li">{`Send invite to our friendly cyborg bot as a Contributor: `}<a parentName="p" {...{"href":"https://github.com/sesheta"}}>{`Sesheta`}</a></p>/home/ochatter/Workspace/github/operate-first/operate-first.github.io/.cache/gatsby-source-git/blueprints/continuous-delivery/docs/setup_cd_pipeline.md: unknown: Expected corresponding JSX closing tag for <br> (14:74)

  12 | <li parentName="ul">
  13 | <p parentName="li">{`AICoE-CI is available as `}<a parentName="p" {...{"href":"https://github.com/apps/aicoe-ci"}}>{`github application`}</a>{`.`}<br>{`
> 14 | Install and configure the app on your GitHub Organization or Repository.`}</p>
     |                                                                           ^
  15 | </li>
  16 | <li parentName="ul">
  17 | <p parentName="li">{`Send invite to our friendly cyborg bot as a Contributor: `}<a parentName="p" {...{"href":"https://github.com/sesheta"}}>{`Sesheta`}</a></p>

  106 |       // Then create the node, as if it were created by the gatsby-source
  107 |       // filesystem plugin.
> 108 |       return createNode(fileNode, {
      |              ^
  109 |         name: `gatsby-source-filesystem`
  110 |       });
  111 |     });

File: node_modules/gatsby-source-git/gatsby-node.js:108:14
```

We might want to explore https://www.gatsbyjs.com/plugins/gatsby-remark-line-breaks/?=gatsby-plugin-mdx or replace `<br>` with `<br />` in https://github.com/operate-first/continuous-delivery/blob/master/docs/setup_cd_pipeline.md tested on my fork [here](https://github.com/oindrillac/continuous-delivery/blob/master/docs/setup_cd_pipeline.md) for which the build completed succesfully.

**Comment by durandom** [comment]
I think we should lint/fix .md files before processing. 
remark plugins can be added to gatsby-plugin-mdx like 

```js
        remarkPlugins: [
          require("remark-lint"),
          require("remark-lint-no-html"),
          // To pass options, use a 2-element array with the
          // configuration in an object in the second element
          // [require("remark-external-links"), { target: false }],
        ],
```

Then you can use remark to fix your markdown like in https://github.com/remarkjs/remark-lint#using-remark-to-fix-your-markdown
Ideally while building the pages, but if that does not work, we could have a npm script executing `remark . --output` as a pre_build script. 

I failed to run this with my cut-n-paste coding skills. @tumido @cfchase have you done this before or do you have a better understanding how this could work?

second @goern @harshad16 - can we have markdown, HTML linting in the bots? So that we don't get broken files into the repos in the first place.

**Comment by tumido** [comment]
Unfortunately this is not about "broken" markdown. Our Markdown is completely valid, HTML tags are valid in Markdown. They are not valid in MDX though. See https://github.com/operate-first/operate-first.github.io/pull/129 description and references.

Our fault is that we're processing all Markdown files as if they were MDX. We're running it all via MDX plugin no matter it's pure Markdown, this is the culprit right here:
https://github.com/operate-first/operate-first.github.io/blob/f6a66ab590c948a3b8abbdc50506683f8102e99b/gatsby-config.js#L23

I suggest we start processing only `mdx` files as MDX and leave Markdown alone -> if we have a Markdown file somewhere which is actually a MDX, we should correct the suffix.

**Comment by tumido** [comment]
![image](https://user-images.githubusercontent.com/7453394/101150524-a5983080-3620-11eb-84eb-3d04a59daaa0.png)
https://github.com/mdx-js/mdx/pull/1039

mind this was merged to their `next` branch - the version we use is using the previous parser, which doesn't change the fact that it won't work even with the new ones. It also further diverges the Markdown and MDX syntax in cases like comments etc. I think we should really treat those as 2 separate languages.

**Comment by cfchase** [comment]
> I suggest we start processing only `mdx` files as MDX and leave Markdown alone -> if we have a Markdown file somewhere which is actually a MDX, we should correct the suffix.

Sounds reasonable to me, but I haven't tried it. I haven't tried running both md and mdx in the same project but seems doable.

**Comment by durandom** [comment]
I went down that road too, using https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-remark as the transformer. 

First I was under the impression, that the MDX plugin is the preferred way now: https://www.gatsbyjs.com/docs/mdx/migrate-remark-to-mdx/ 
But I couldn't find any evidence for that :) Maybe I was interpreting too much.

Makes sense. The external repos are all using only `.md` anyways...
