### ISSUE TITLE
Create Operate-First Gatsby Theme

### ISSUE THREAD

**Issue by anishasthana** [operate-first/operate-first.github.io-old#145]
Since we are aiming to have consistent-looking docs across operate-first, internal data hub, and upstream ODH, we should publish a proper theme on gatsby that can be installed for any document sites. This way we'd only have to make changes to the theme in one location and have them trickle down to all the deployments. CC @tumido

**Comment by tumido** [comment]
Something like https://github.com/jschuler/gatsby-theme-patternfly would do, right? Just updated to Paternfly 4 + our custom components.

**Comment by anishasthana** [comment]
Yeah I think that'd be perfect.

**Comment by tumido** [comment]
https://github.com/jschuler/gatsby-theme-patternfly/issues/15

**Comment by tumido** [comment]
More questions asked https://github.com/patternfly/patternfly-org/issues/2312

**Comment by anishasthana** [comment]
@oindrillac fyi

**Comment by durandom** [comment]
@anishasthana do you have a pointer where you're doing your internal deployment? For starters I would work with a fork/rebase relationship of the repos and extract all stuff into configurations

@cfchase should decide if he wants a theme for all his MODH work

**Comment by anishasthana** [comment]
It's on internal gitlab unfortunately: as of now I had to do a pretty ugly rip and tear.
https://gitlab.cee.redhat.com/data-hub/dh-user-docs

**Comment by tumido** [comment]
So, Patternfly community finally replied. They don't maintain any of it and don't plan to support Gatsby. We would need to update it ourselves and create yet another theme/package if we want to support this. Leaving it up and open - I think this would be a nice Internship project.

/label hacktoberfest
