### ISSUE TITLE
document setup process

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#15]
document the steps to re-create a similar site with CI build integration

**Comment by goern** [comment]
1. create a utility container with gatsby
2. create tekton task to `gatsby build`
3. create pipeline triggered by push to master to 
3.1. pull master
3.2. `gatsby build`
3.3. * commit to `gh-pages` branch

/kind feature
/assign @harshad16 
/priority important-soon

**Comment by goern** [comment]
where is all my cyborgs to help me?!

**Comment by harshad16** [comment]
@goern thanks for structing the working point.
i will work on it starting next week in aicoe-ci. 
https://github.com/AICoE/aicoe-ci/issues/59

i would like to discuss the trigger part of it.
trigger on each push seems , to heavy for current ci infrastructure(psi).
we can have it trigger via an issue or on tag release. 
i personally would like an issue, as through that ci would be able to comment on the issue while working through the task.

**Comment by harshad16** [comment]
sorry this done in the time period mentioned.
revisiting this now.  bring back the life-cycle of this issue to active.

**Comment by harshad16** [comment]
Recollecting all the thought, this process is already in place.
aicoe-ci builds the image for the operate-first app and travis ci takes care of updating the gh-pages.
Please let me know if further action is to be added to this. we can close this issue.

**Comment by goern** [comment]
I think we need a tekton task that updates gh-pages, and a pipeline that uses the task and then builds the image
