### ISSUE TITLE
Relative links download *.ipynb files instead of redirecting to the correct page 

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/operate-first.github.io-old#153]
Relative links download *.ipynb files instead of redirecting to the correct page. 

 I am using [this *.md file](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/README.md) as both the readme for the ocp-ci repo as well landing page on operate first. I've used relative links so that the links should behave the same on github and op1st. The relative links seem to work fine on github but on op1st only the *md files redirect properly the *.ipynb do not. They download the file instead of redirecting to the correct page. Here is an example of a relative link that I am using. 

***.ipynb:**
```
* [Indepth TestGrid exploratory data analysis for machine learing](notebooks/TestGrid_indepth_EDA.ipynb)
```
***.md:**
```
[Detailed project description](docs/failure-type-classification-with-the-testgrid-data-project-doc.md)
```

Is this a limitation of the op1st site? Or do we need to handle *ipynb links differently?

**Comment by durandom** [comment]
I'll have a look
/assign @durandom
