### ISSUE TITLE
All notebook in a particular project under a single tab

### ISSUE THREAD

**Issue by SankBad** [operate-first/operate-first.github.io-old#157]
Hi, 

I have a suggestion or feedback. 
Currently, we have different tabs for each of the notebooks. Since the number of notebooks is increasing this vertical list can go long. Also, some times notebooks can be really long. Please find the screenshot. 
![image](https://user-images.githubusercontent.com/29823086/101784201-32cc0100-3ac9-11eb-969e-72cc29284082.png)

Instead, we can create a demo notebooks section for each project. In that particular page, we can give users a brief intro about each notebook. If the users are interested he can expand the notebook.

For reference, I am attaching the demo notebook sections of [Databricks websites](https://docs.databricks.com/spark/latest/structured-streaming/demo-notebooks.html).

**Comment by SankBad** [comment]
CC: @oindrillac , @MichaelClifford

**Comment by durandom** [comment]
I would not rely too much on the left hand navigation. You can't add a nav item for every page/notebook/doc you add.
Try to use one or two entry documents and link from them. If those are relative links they'll work inside your repo and on this website.

See https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax
and 
https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/working-with-advanced-formatting
