### ISSUE TITLE
build and publish operate-first gatsby image

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#16]
what does that image contain?
how do we publish the image to https://quay.io/organization/aicoe

**Comment by HumairAK** [comment]
Not sure about the former, but for the latter - set up the build pipeline via these instructions: https://github.com/AICoE/aicoe-ci#setting-aicoe-ci-on-github-organizationrepository 

for the `continuous-deployment` repo we're doing tag builds, but you can also set up automatica pr merge -> tag -> build as well afaik.

**Comment by goern** [comment]
do we want to have (a) a container image that can do s2i or (b) do we want it to be used in tekton pipelines?

I would go w/ (b) only...

**Comment by cfchase** [comment]
Right now, the simplest starting point for me was a nodejs container built with s2i.  I figured that would be the easiest thing to automate and I could do using any pipeline.

I added a Makefile in my WIP branch with some associated scripts.
https://github.com/operate-first/operate-first.github.io/compare/master...s2i

I'll take a look at the Tekton continuous-deployment stuff

**Comment by goern** [comment]
and s2i compliant image is good enough, @harshad16 can easily wrap it up in a tekton task, its some boilerplate from https://github.com/tektoncd/catalog/tree/master/task/s2i/0.1

**Comment by harshad16** [comment]
we can setup an image repository in aicoe, and then can setup bots in quay.io which can be used for pushing the image, through a ci system which builds it.
so in this scenario, 
- setup an image repository in aicoe: The developer of aicoe has to do this, and attach `aicoe+aicoe_pusher` to that repository.
- All the rest can be configured through aicoe-ci.

**Comment by durandom** [comment]
@cfchase I think if you finish your WIP branch so that we can build an s2i image locally and deploy it to a namespace would be good. Then @harshad16 can take it from there.

We'd like to look into running another version of this operate-first site in PSI and quicklab soon 

/cc @oindrillac

**Comment by durandom** [comment]
Or is https://github.com/operate-first/operate-first.github.io#running-on-openshift containing all we need?

**Comment by cfchase** [comment]
@durandom I merged it in awhile ago, so it should be done.  If it's not doing what you need, let me know

**Comment by 4n4nd** [comment]
@cfchase I was trying to create a new image from this repo but it failed with the following error:
```
ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

unknown: Unexpected token (226:1)

224 | `}</code></pre>
225 | </details>
> 226 | <!-- markdownlint-restore -->
|  ^
227 |     </MDXLayout>
228 |   )
229 | };/opt/app-root/src/continuous-deployment/docs/downstream/on-cluster-persistent-storage/README.md: unknown: Unexpected token (226:1)

224 | `}</code></pre>
225 | </details>
> 226 | <!-- markdownlint-restore -->
|  ^
227 |     </MDXLayout>
228 |   )
229 | };
```
The error seems to be from a file in a different repo ([here](https://github.com/operate-first/continuous-deployment/blob/master/docs/downstream/on-cluster-persistent-storage/README.md))

This looks like it is building the web page during the image build. We might need to add an "image build test" in all our repos to prevent issues like this.

**Comment by cfchase** [comment]
@4n4nd I was just looking at this because it was failing it's [Travis deployment](https://travis-ci.org/github/operate-first/operate-first.github.io/builds/737554352).

https://github.com/operate-first/operate-first.github.io/pull/48 should resolve it. It built fine for me now.  The remote repo was added as an example and has stuff not meant for publication.

**Comment by 4n4nd** [comment]
@cfchase can a similar issue occur from markdown files that are meant for publication?

**Comment by cfchase** [comment]
> @cfchase can a similar issue occur from markdown files that are meant for publication?

Yes, the build would still benefit from CI.

**Comment by tumido** [comment]
Site is served via gh-pages and we probably don't need to change that for a while... Feel free to reopen if it becomes relevant again.
