### ISSUE TITLE
Add TestGrid data analysis video to YT and website

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#161]
- [x] Upload video to YT channel
- [x] Add Video to Website 

@MichaelClifford can you please provide me with a suitable Title and a short 1-2 lines description for the YouTube video.

**Comment by MichaelClifford** [comment]
@oindrillac is there an existing youtube channel I can upload the video to? 

Here is a title and description. Let me know if you have any edits : ) 

**Title**: Access TestGrid data for analysis with python 

**Description**: Introduction to the AI supported continuous integration project started by members of Red Hats's AI Center of Excellence. The first of a series, this video describes the TestGrid ecosystem and data source as well as existing tools to access and prepare data for analysis with python.

**Comment by oindrillac** [comment]
@MichaelClifford I have uploaded it to our [Operate First channel](https://www.youtube.com/channel/UCe87bwqlGoBQs2RvMQZ5_sg). Here you go - https://www.youtube.com/watch?v=lY75bDv6kd4&feature=youtu.be :tada:
