### ISSUE TITLE
Add Initial EDA on cloud price data video to YT and website

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#162]
- [x] Upload video to YT channel
- [x] Add video to website

@aakankshaduggal can you provide me with a suitable Title and 1-2 line description for the YouTube video?

**Comment by aakankshaduggal** [comment]
*Title*: Cloud Price Analysis on AWS Data

*Description*: Introduction to the Cloud Price Analysis project started by members of Red Hats' AI Center of Excellence. The first of a series, this video gives an overview of the Project Statement and Exploratory Data Analysis in the JupyterHub environment.

**Comment by aakankshaduggal** [comment]
@oindrillac Here is a title and a description. Let me know if you have any suggestions. :smile:

**Comment by oindrillac** [comment]
@aakankshaduggal please find the uploaded video here : https://www.youtube.com/watch?v=jne4auRnxJ4&feature=youtu.be
