### ISSUE TITLE
map content in our GH repos vs what's available on the website

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#167]
@oindrillac can you create a spreadsheet that lists all our repos at

* https://github.com/aicoe
* https://github.com/aicoe-aiops
* https://github.com/operate-first

and mark those that are configured here as content?

I'd like to see what we're missing

**Comment by oindrillac** [comment]
@durandom here you go - https://docs.google.com/spreadsheets/d/1eJspSq8db7k8wdbzr0uyYI9wN6Az1fNTa3yJTqqK1OY/edit?usp=sharing

**Comment by durandom** [comment]
thanks.

Next we should have a metric for each added repo, on how much of the content is actually accessible. I.e. can be accessed by just clicking links.

For the not added repos, we should determine when they were last active and how much content is there (.md files)

cc @goern is this something we could use your GH analysis tools for?

**Comment by durandom** [comment]
I.e. I dont want to make this a manual process, but more like a dashboard to see the current status
