### ISSUE TITLE
Rendering plotly images in the notebooks

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/operate-first.github.io-old#170]
In one of the notebooks, I'm using plotly interactive graphs. However, it is not being rendered currently. For example, see this [blog](https://www.operate-first.cloud/data-science/time-series/notebooks/ts-2-visualization.ipynb). Gatsby has a support for plotly images and I guess it can be integrated with blog posts as well. Is it fairly straightforward or would it be a heavy feature request?

**Comment by durandom** [comment]
https://elcess.us/Integrating-Plotly-with-Gatsby/
https://janosh.dev/blog/gatsby-interactive-plots

I'll look into this

**Comment by Shreyanand** [comment]
@durandom did you get a chance to see if this works?

**Comment by hemajv** [comment]
(Related issue: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/238)

Took a look at the above mentioned blogs and tried to implement these workarounds. However, the blogs mention ways for rendering the plotly graphs/charts within the HTML page alone and does not seem to work or be applicable for rendering them within Jupyter notebooks. There seems to be no official support for enabling these interactive charts to be rendered within notebooks, I created some upstream [issues](https://github.com/gatsbyjs/gatsby/issues/31125) and [discussions](https://github.com/gatsbyjs/gatsby/discussions/31126) to see if we can get some more help from the Gatsby community, but don't see anything available in the near future.

I think we should use libraries like `seaborn` with some additional `ipywidgets` (related issue where we are looking into this: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/217) for creating basic charts in the notebooks and use a dedicated visualization tool for more advanced interactive charts/graphs.
