### ISSUE TITLE
travis build for PRs

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#174]
@cfchase @tumido can we enable builds for PRs here? 
Or would this result in a deploy? 
Do we need some settings in `.travis.yml` ?

I'd like to see if https://github.com/operate-first/operate-first.github.io/pull/173 gets build successfully

**Comment by tumido** [comment]
Our current travis settings for this repo is limited to `master` branch and it will result in a deploy. We'd need to adjust that for PR builds... We probably need to add a PR specific `npm run` script and pass that to the travis config.

@cfchase do you have anything like it set up for any other repo so we can pull the config from there?

**Comment by HumairAK** [comment]
afaik this is done.
