### ISSUE TITLE
Create a better 404 page

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#176]
Current 404 page when hit a bad url just says not found without any other useful info.

We should add more information to this page which encourages the user to reach out to an email address or open an issue at a repo. 

See example below

**Comment by oindrillac** [comment]
We currently have this
![image](https://user-images.githubusercontent.com/32435206/104501475-c6538e80-55ad-11eb-9ff2-5b5714c5fbb5.png)


Example of a good 404 page
![image](https://user-images.githubusercontent.com/32435206/104501442-b8057280-55ad-11eb-9110-13483374db73.png)

**Comment by tumido** [comment]
Example cloud.redhat.com 404 page (patternfly approved): https://cloud.redhat.com/asdasda

![image](https://user-images.githubusercontent.com/7453394/104701217-6bd54200-5715-11eb-9425-ac90c02c97c5.png)
