### ISSUE TITLE
Update CSS and format of document posts

### ISSUE THREAD

**Issue by cfchase** [operate-first/operate-first.github.io-old#18]
Tracking item to review the look of the documents and add fields to front matter like:
- permalink
- date created
- authors
- tags

**Comment by oindrillac** [comment]
Nicely formatting those metadata fields would be great @cfchase.
Also, I like the CTA buttons here in this [blogpost](https://airbnb.io/projects/airflow/). As you are looking into some formatting of the blogpost, can we add CTA buttons similar to above w/ links to useful resources like Git Repo, public JupyterHub Instance etc within the blog?

**Comment by cfchase** [comment]
Should break out patternfly as a theme.  Perhaps similar to:
- https://github.com/patternfly/patternfly-org
- https://github.com/jschuler/gatsby-theme-patternfly
