### ISSUE TITLE
Aakanksha #5 Website User Testing

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/operate-first.github.io-old#184]
*Date of test* -  01/14/2021

## Identified Bug
Identify atleast one bug - could be a broken link, formatting issue, etc

1. 
* Document URL - Documents for Data Science like [1](https://www.operate-first.cloud/data-science/categorical-encoding/docs/blog/blog.md) and [2](https://www.operate-first.cloud/data-science/configuration-files-analysis/docs/blog/configuration-file-analysis-blog.md) 
* Description of Bug - We could either get rid of the tags because initially, we had planned to use them for stasis or we could come up with using these tags for searching across the documents.
* Issue/PR - 

## Feature Enhancement
Identify atleast one feature that could be added to the website - this could be from a user experience POV.

1. 
* Description of feature -
* Issue/PR - 

## Missing Documentation
Identify atleast one artifact (document or video) that is missing, that has not been added to the website as yet.

1. 
* Link to Git document or YouTube video -
* Issue/PR -

**Comment by oindrillac** [comment]
:+1: for removing the tags since we are no longer using statis reactor.
We have an issue here for site wide search https://github.com/operate-first/operate-first.github.io/issues/25
