### ISSUE TITLE
Update `Users` tab in https://www.operate-first.cloud/users/

### ISSUE THREAD

**Issue by anishasthana** [operate-first/operate-first.github.io-old#191]
I think clicking on the `Users` Button in the top nav bar should take folks directly to https://www.operate-first.cloud/users/support/. The content on here seems like the most useful for a general person. Thoughts?

**Comment by oindrillac** [comment]
@anishasthana +1 with that. And I plan on updating this and the other sections too. :+1: 
@hemajv had opened this issue here https://github.com/operate-first/operate-first.github.io/issues/182

**Comment by HumairAK** [comment]
looks like this was resolved
