### ISSUE TITLE
Link JupyterHub monitoring Grafana Dashboard to website

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#193]
Link Grafana dashboard https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/YuYfkHYMk/jupyterhub-usage?orgId=1 from Users tab of website.

**Comment by chauhankaranraj** [comment]
I **_really_** like this dashboard, thanks for putting it together folks! :smile:

Just wanted to clarify though, do the `Pod CPU Usage` numbers shown here need to be multiplied by 100 or am I really only using 0.7% of the CPU?
