### ISSUE TITLE
Find a nice logo for Operate First

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#2]
maybe somebody can draw? or find a CC image...

**Comment by goern** [comment]
what about this: https://thenounproject.com/term/operator/1156395/

**Comment by tumido** [comment]
1. What about something like this? https://thenounproject.com/term/ouroboros/2906151/
  Ouroboros kinda resembles the CI/CD process, it's a never ending circle. It also looks like an capital "O" letter from "Operate". We can maybe put something in the middle? Another icon, that would signify what is being operated maybe?

2. Operate 1st - capital letters also reminds me of binary "01", that might be also an interesting avenue to discover...

**Comment by goern** [comment]
I like 2. :)

**Comment by goern** [comment]
“Operator” icon by goyacommae from the Noun Project.

https://thenounproject.com/term/operator/1196725/

**Comment by goern** [comment]
![noun_operator_1196725](https://user-images.githubusercontent.com/260331/93567564-1ec3a800-f98f-11ea-9377-09720b76448f.png)

**Comment by goern** [comment]
looks like an On/Off ("have you tried to switch it off and on again?"), looks like this continouousoosss snake thingy, and it is **O**p**1**st

**Comment by tumido** [comment]
That is genius! :smile: It's all of them together! :+1:  It also looks like a child scribbling, which perfectly describes the project so far. :slightly_smiling_face: I mean.. the slightly "amateurish" look gives it an extra dimension. I like the irony in that :+1:

**Comment by goern** [comment]
🤘

**Comment by durandom** [comment]
I think we need to credit the author of the logo

This icon is licensed as Creative Commons CCBY
