### ISSUE TITLE
Certificate warning for https://operate-first.cloud

### ISSUE THREAD

**Issue by llunved** [operate-first/operate-first.github.io-old#207]
The TLS cert is github and Firefox complains.

**Comment by tumido** [comment]
Thank you!

/assign @goern
/cc @oindrillac

**Comment by goern** [comment]
It seems to happen with `curl -vk -X HEAD https://operate-first.cloud` (hosted at GH), as github redirects to www.operate-first.cloud the cert used is correct.

let's monitor this, maybe its a GH hickup

/sig devops

**Comment by HumairAK** [comment]
resolved
