### ISSUE TITLE
Link YouTube Channel from Website

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#213]
Link the YouTube channel from Website. 
Add YouTube icon to Top right corner on the Masthead of the Website which links to the channel or add a separate Videos/Blog page.

**Comment by aakankshaduggal** [comment]
I like this idea of adding the youtube channel to the footer. Something like this : 
![image](https://user-images.githubusercontent.com/26301643/111167076-1ed7e580-8577-11eb-8d57-9117f9b5e5ae.png)

We could also add our github repo in the footer.

**Comment by tumido** [comment]
I think the masthead is a more prominent space though. :slightly_smiling_face:
