### ISSUE TITLE
Create Medium Account for Operate First

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#214]
Create a Medium.com account for operate first which can be used to re-purpose and post some of our content linking back to the website.

**Comment by goern** [comment]
please check with @Fridex Medium is not always very friendly if it comes to content licensing and reuse.

**Comment by fridex** [comment]
Articles published on medium are not always reachable to users - medium restricts the number of views per user that is not that open. I found [dev.to](https://dev.to/) community more open.
