### ISSUE TITLE
Fix occurrence of 2 scroll bars in website

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#215]
The site footer leads to occurrence of 2 scroll bars on the website.
![image](https://user-images.githubusercontent.com/32435206/111166800-dcaea400-8576-11eb-9f9f-788245aad2da.png)

Fix that to have only one scroll bar such that the footer appears right below the "Contribute to this page button"

**Comment by tumido** [comment]
Resolved
