### ISSUE TITLE
How to trigger a website rebuild on content update 

### ISSUE THREAD

**Issue by tumido** [operate-first/operate-first.github.io-old#216]
This website aggregates content from many repos. We would like to be able to trigger a build on any content update. Either via bots or manually, or via chat-ops or on PR merge in that other repo (based on PR label perhaps?).

/cc @goern @oindrillac any ideas?

**Comment by goern** [comment]
well, we can turn the website build into an OpenShift/Tekton Pipeline and trigger it on 'push to master'

**Comment by tumido** [comment]
That is fine for build triggering from this repo. But we need to trigger it also on update on any of these remote content locations:

https://github.com/operate-first/operate-first.github.io/blob/master/gatsby-config.js#L160-L316

It's a static website aggregating dynamic content across many repos.

We may need some more advanced logic for triggering from PR merges on dependency repos...

**Comment by harshad16** [comment]
What is the current flow?
on update of the repositories listed in the gatsby-config, does the maintainer execute gatsby build and update the gh-pages?

linking this here, as this was something suggested earlier: https://github.com/operate-first/operate-first.github.io/issues/15

**Comment by tumido** [comment]
Current flow:

The only way to trigger a build is to make any commit on `master` branch in https://github.com/operate-first/operate-first.github.io

Travis is listening for push to `master` events and triggers the build.

It can be an empty commit but nobody is actually allowed to push to `master`, therefore it kinda requires a PR/code change... which is unfortunate.

**Comment by larsks** [comment]
Could you install a webhook into all those repositories that would post a notification, and have a single receiver that would respond to that by updating the website? Or if updates don't *really* need to be real time, what about just periodically (hourly?) monitoring those repositories for new commits, and triggering a change if any one of them has an update?

**Comment by tumido** [comment]
I mean if it's just a dumb hourly rebuild without any repo update checks.. I con't care. It would be an usable solution.

On the other hand, I would expect better from us. :smile:

**Comment by harshad16** [comment]
we could have bots functioning on the issue, I mean to say, like we can have a temple issue on the related component repos, and on the issue creation of these, a bot would trigger and update the repo(like same like travis flow which updates the gh-pages).

**Comment by tumido** [comment]
Resolved via #334 

I know that we're not doing reactive (on activity on different repos) build triggers, which was the purpose for this issue. However we're issuing a rebuild daily instead. I think that should be "enough" for now. We also have a manual trigger now (see #335 ) so if there's a need to immediately trigger a new build we can.

If the solution is not enough, please reopen the issue and offer a better implementation.
