### ISSUE TITLE
Add a "community" page to website

### ISSUE THREAD

**Issue by larsks** [operate-first/operate-first.github.io-old#221]
On the current website, the link to the public slack invite is...subtle. Unless you know it's there it's not necessarily discoverable. I thought perhaps we should add an explicit "community" page that explicitly calls out the link to slack, perhaps the support repository, etc.

**Comment by HumairAK** [comment]
Link is now found in support readme along with an icon on the website at the top right, I think the locations are relatively "in your face", there's also a separate community repo now as well -- so closing, re-open if someone feels differently!
