### ISSUE TITLE
Error while trying to build locally

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/operate-first.github.io-old#227]
When we try to build locally, using `make dev` got this error 

![image](https://user-images.githubusercontent.com/26301643/113335080-781f7300-92f2-11eb-880c-c7a83805984f.png)

**Comment by tumido** [comment]
Hey @aakankshaduggal ! I can't reproduce this locally, this seems to be related to your local setup.

Let try doing this:
1. Please checkout to the latest master
2. Delete `.cache` and `public` folders
3. Do `npm install` to get all the dependencies which may have changed over time installed from `package-lock.json` 
4. Run `make dev` again

If the problem occurs again, please post a full log in here.

You can verify the file was properly pulled from git by checking on `.cache/gatsby-source-git/data-science/ceph-drive-failure/notebooks/experimental/multivariate_forecast_smart_metrics.ipynb` file. :slightly_smiling_face: 

Let me know if it worked or not. :+1:

**Comment by aakankshaduggal** [comment]
Thank you @tumido. This resolved the issue. :+1:
