### ISSUE TITLE
Add logo to website

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#23]
- [x] Use logo from [#2](https://github.com/operate-first/operate-first.github.io/issues/2) and create logo with the text "Operate First"

- [x] Add operate-first logo to website

- [x] Add just the logo as a favicon

**Comment by oindrillac** [comment]
Here is our Operator icon by goyacommae in Red Hat Display Heavy font Camel cased
![operate-first](https://user-images.githubusercontent.com/32435206/93937211-5adf6b80-fcf5-11ea-937c-080dda89466f.png)
Red Hat Display Heavy Upper cased
![operate-first-caps](https://user-images.githubusercontent.com/32435206/93937279-764a7680-fcf5-11ea-8a84-6fef52d08019.png)
Manrope Bold Upper cased
![operate-first-inter-caps](https://user-images.githubusercontent.com/32435206/93937379-a85bd880-fcf5-11ea-901f-5a1935a2ec49.png)

thoughts?

**Comment by goern** [comment]
RH font!! :)

**Comment by cfchase** [comment]
WIP merged.  I put the png with the RH font, reversed it so it worked on the black background.  Also fixed the favicon to match.  @oindrillac if you update the logo just let me know.  Also, an svg would be a bit sharper if that's available, and if you want to export a white version from original that'd also be good.  Let me know what you guys think.

![Screenshot from 2020-09-29 17-09-27](https://user-images.githubusercontent.com/1448375/94615928-8ecb0b80-0276-11eb-8517-a72a081f577d.png)

**Comment by oindrillac** [comment]
@cfchase looks good. I am attaching the high resolution white png and svg herewith. I also tweaked the spacing b/w alphabets and b/w the 2 words a little bit. I was having some trouble exporting .svg through Gimp, so had to use an online software, not sure if its perfectly formatted. Hope one of these work.
[operate-first-logo-hi-res-white.zip](https://github.com/operate-first/operate-first.github.io/files/5307441/operate-first-logo-hi-res-white.zip)

**Comment by cfchase** [comment]
@oindrillac try inkscape.  It's the bees knees for svgs and logos!  Generally I think it's nice to start with svg and export to other less accurate representations.

**Comment by oindrillac** [comment]
ah looks neat. Will try that out. Thanks @cfchase

**Comment by cfchase** [comment]
> @cfchase looks good. I am attaching the high resolution white png and svg herewith. I also tweaked the spacing b/w alphabets and b/w the 2 words a little bit. I was having some trouble exporting .svg through Gimp, so had to use an online software, not sure if its perfectly formatted. Hope one of these work.
> [operate-first-logo-hi-res-white.zip](https://github.com/operate-first/operate-first.github.io/files/5307441/operate-first-logo-hi-res-white.zip)

@oindrillac I updated with the new PNG.  Since PNGs don't scale well, I don't see much difference.  However, on the SVG, doesn't seem to show the icon.  Looking at the SVG I think it just took the PNG and embedded it in an SVG format, so it probably wouldn't scale, either, since it's just and SVG wrapping the PNG and not a scalable vector.
