### ISSUE TITLE
Create Twitter Account

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#231]
create a twitter account for community updates and sharing stuff.

**Comment by oindrillac** [comment]
FTR: spoke to @goern about how and if https://twitter.com/ThothStation is configured. Seems like it is a personal account with a shared password which anybody can tweet from, no bots involved.

**Comment by tumido** [comment]
I'd like for us to have something like this set up:

https://github.com/gr2m/twitter-together

Basically we would tweet via PR, once merged it's submitted to Twitter.

**Comment by oindrillac** [comment]
oh awesome! just what i was looking for. thanks for sharing @tumido

**Comment by tumido** [comment]
Yeah, I've been eyeing that project for a while. :smile: I think I've already linked it in some issue, but apparently not. :smile:

**Comment by goern** [comment]
> I'd like for us to have something like this set up:
> https://github.com/gr2m/twitter-together

I want this too, refactored, as a Tekton pipeline! :)

**Comment by oindrillac** [comment]
We now have a twitter account - https://twitter.com/OperateFirst
and a repo to collaboratively Tweet through PRs 🙂  - https://github.com/operate-first/operate-first-twitter
Follow, Re-tweet and share! 🐦
