### ISSUE TITLE
Wrong horizontal alignment in docs?

### ISSUE THREAD

**Issue by paoloantinori** [operate-first/operate-first.github.io-old#239]
Hi, I'm not sure if this change is deliberate or a side effect of some fiddling with HTML and css, but the docs has started to render with a funny a not very readable `text-align: center`:

![Screenshot from 2021-04-24 07-48-39](https://user-images.githubusercontent.com/1520602/115949016-1c4fa080-a4d2-11eb-9c6d-3ff521533501.png)

![Screenshot from 2021-04-24 07-52-50](https://user-images.githubusercontent.com/1520602/115949014-1659bf80-a4d2-11eb-922d-fa8b87cb7839.png)

**Comment by tumido** [comment]
Yes, the site got broken by #235 , we'll fix it asap. Thank you for reporting this. :slightly_smiling_face: :+1:

**Comment by tumido** [comment]
Will be resolved by: https://github.com/operate-first/operate-first.github.io/pull/240
