### ISSUE TITLE
Add overview of all projects

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#24]
- [ ] Add AIOps project overviews from [doc](https://github.com/aicoe-aiops/data-science-workflows/blob/master/docs/aiops-projects.md) to operate-first repo.
- [ ] Add overview as an item on left toc, and find a suitable header - probably "Projects Overview"

**Comment by aakankshaduggal** [comment]
Wanted to confirm which folder should we add this document to?
[Here](https://github.com/aakankshaduggal/operate-first.github.io/tree/master/content/docs) or should we make a separate folder for documentation?

**Comment by aakankshaduggal** [comment]
ping @oindrillac @hemajv

**Comment by durandom** [comment]
@aakankshaduggal yes, that folder is good. Also make sure to only include public projects
