### ISSUE TITLE
Telemetry and Bugzilla EDA notebooks not showing up on side panel

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/operate-first.github.io-old#249]
The Telemetry and Bugzilla EDA notebooks that were added a few days back, are however visible using the links : [Telemetry EDA](https://www.operate-first.cloud/data-science/ocp-ci-analysis/notebooks/data-sources/Telemetry/telemetry_EDA.ipynb) and [Bugzilla EDA](https://www.operate-first.cloud/data-science/ocp-ci-analysis/notebooks/data-sources/Bugzilla/bugzilla_EDA.ipynb) but not showing up on the side panel.

**Comment by oindrillac** [comment]
@aakankshaduggal it seems that the urls in data-science.yaml #247 point to `/data-sources/Telemetry/telemetry_EDA.ipynb` which does not seem like the correct full href.
Fixing it to `data-science/ocp-ci-analysis/notebooks/data-sources/Telemetry/telemetry_EDA.ipynb`
and `data-science/ocp-ci-analysis/notebooks/data-sources/Bugzilla/bugzilla_EDA.ipynb`
should work

**Comment by aakankshaduggal** [comment]
Awesome. I will do that now. Thanks @oindrillac
