### ISSUE TITLE
render sphinx API docs

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#26]
As per https://github.com/operate-first/operate-first.github.io/issues/9#issuecomment-697160394

we would be happy if we could include our sphinx-generated API doc.

Is sphinx based on asciidoc? IIRC it's extracting the inline docs to an HTML output. 
See https://www.gatsbyjs.com/plugins/ for plugins, maybe there's a transformer for an output that can be generated by sphinx.

**Comment by cfchase** [comment]
https://www.sphinx-doc.org/en/master/usage/markdown.html
