### ISSUE TITLE
Clarify information on the Operations page for users

### ISSUE THREAD

**Issue by margarethaley** [operate-first/operate-first.github.io-old#260]
Information on the Operations page could be slightly more polished in order to appeal to users. I want to make sure the page is easy to read / understand and provides a simple explanation of what can be found in the tabs. 

- improve phrasing/grammar
- make the meaning of GitOps more explicit
- link to more info on GitOps if the user wants to learn more
- add toolbox heading and info to main page

**Comment by oindrillac** [comment]
related https://github.com/operate-first/community/issues/9
