### ISSUE TITLE
Update link for the new Jupyterhub monitoring dashboard

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/operate-first.github.io-old#262]
https://www.operate-first.cloud/users/sre/runbooks/jupyterhub.md should reflect the link to the updated dashboard.

**Comment by Shreyanand** [comment]
@tumido does the dashboard need to be changed more before it can be published here?

**Comment by tumido** [comment]
Nope, I think the dashboard is final, at least for now, until we can consume events from loki as well. I'll update the link.
