### ISSUE TITLE
Migrate repo to travis-ci.com from travis-ci.org

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#266]
Our travis-ci.org repository is now read-only on https://travis-ci.org/github/operate-first/operate-first.github.io and has been automatically deactivated which makes us unable to trigger a new build for website content changes.

We need to migrate to travis-ci.com to enable us to Trigger builds again.

Can someone with admin access to the operate-first organization [set this repository up for migration](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository)?.

**Comment by tumido** [comment]
I hope i followed the process right (initially the migration button was grayed out for us, requiring me to sign the org up for some beta migration plan). Now the repo appears on travis com website...

https://travis-ci.com/github/operate-first/operate-first.github.io

Let me know if there's still any issues with the setup.

**Comment by oindrillac** [comment]
thanks @tumido, able to trigger builds again 👍
