### ISSUE TITLE
Link Operate First Community Manifesto to repo

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#27]
- [ ] Link [operate first community manifesto](https://openinfralabs.org/operate-first-manifesto/) from Website.

@cchase is there a way to redirect an item in the toc on the left to an external url?

**Comment by durandom** [comment]
@oindrillac I would not redirect menu/toc entries. That sounds counterintuitive to me. For content like this, let's create a "resources" or "links" page

**Comment by oindrillac** [comment]
@durandom sounds good!
