### ISSUE TITLE
Front page not responsive to mobile

### ISSUE THREAD

**Issue by quaid** [operate-first/operate-first.github.io-old#291]
I don't know if this is a new issue or an existing one with the site CSS. When viewed on a mobile device, it does not offer a modified, responsive mobile experience, nor does it offer (on Chrome on Android) full scrolling or ways to get access to the edges of content.

Landscape view

![Screenshot_20210817-213615](https://user-images.githubusercontent.com/112760/129838719-54aa878f-f91a-4ea0-b232-98552969bcd2.png)

----

Portrait view

![Screenshot_20210817-213522](https://user-images.githubusercontent.com/112760/129838722-5577fcd7-8677-4dfa-bed9-ca036c594322.png)

**Comment by tumido** [comment]
I think #288 fixes most of the issues, I think that's a good starting point. WDYT?
![Peek 2021-08-18 22-13](https://user-images.githubusercontent.com/7453394/129965823-4e80be53-8f5b-4633-b94d-39cc25270bb2.gif)

The unequal button width is a Patternfly issue, we can look into it and workaround it by some CSS and the footer is also a problem that we'll need to look into next.

**Comment by quaid** [comment]
Oh, so much better @tumido ! Yeah, my mobile view looks just like yours, same unequal buttons and footer issue.

Shall we see if anyone from Patternfly would like to help?

We can keep this issue open as we fine tune. Thanks!

**Comment by tumido** [comment]
I think I can try doing something about it first, I think it'll be faster than involving multiple teams. :slightly_smiling_face:
