### ISSUE TITLE
"Operate First Support", "Toolbox", "Additional Resources" duplicating on each side panel

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#294]
The "**Operate First Support**", "**Toolbox**" & "**Additional Resources**" panel items now appear on each of the 4 side panels in Data Science, Users, Operations and Blueprints.

![image](https://user-images.githubusercontent.com/32435206/129948918-9f3cf671-b70d-41a4-b23b-150ee7a62f84.png)

Is this an intentional change? I think these are valuable resources. However, is it necessary to duplicate these items on every side panel for all the sections?

**Comment by tumido** [comment]
Sigh... Yup, my fault again. I'll send a PR shortly.😉
