### ISSUE TITLE
Broken links in the users/support page

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/operate-first.github.io-old#297]
The following highlighted links in the [supports page](https://www.operate-first.cloud/users/support/) don't seem to be working properly:
![image](https://user-images.githubusercontent.com/22333506/130258370-448053ef-f64a-43f7-b186-fc5727a4aef2.png)

**Comment by oindrillac** [comment]
thanks @4n4nd! do you have the right links?

**Comment by oindrillac** [comment]
just noticed that the "here" link says Application Not Available, we should change that too.
![image](https://user-images.githubusercontent.com/32435206/130259500-d38ff86e-c706-46e8-8eb3-e3931d1a3786.png)
 do you have the new link?

**Comment by 4n4nd** [comment]
@HumairAK sent me the correct links:
1. https://github.com/operate-first/support/tree/main/docs/odh
2. https://github.com/operate-first/support/tree/main/docs/kubeflow

**Comment by schwesig** [comment]
/triage accepted
/kind cleanup
/priority important-soon

https://github.com/operate-first/operate-first.github.io/issues/311

**Comment by HumairAK** [comment]
this is now resolved
