### ISSUE TITLE
Create bot account with Personal Access Token for use for CI CD

### ISSUE THREAD

**Issue by cfchase** [operate-first/operate-first.github.io-old#3]
Currently, operate-first.github.io uses Travis for CD.  It pushes built assets to gh-pages branch which is served on https://operate-first.github.io/.  This requires a "personal access token" with repo access.

https://travis-ci.org/github/operate-first/operate-first.github.io

Instead of using a real human personal access token, we should create a bot user with access to push the deployed assets.

**Comment by cfchase** [comment]
Side note: I'm using Travis, but the CD pipeline is simple. We could change it to use whatever you want.

**Comment by goern** [comment]
@sesheta is now part of the team, all repos are added to prow...

**Comment by durandom** [comment]
> @sesheta is not part of the team, all repos are added to prow...

not sure what that means, can we stick to Travis CI and create an access token for @sesheta to perform pushing?

Right now the updates are pushed by "Travis CI User" https://github.com/operate-first/operate-first.github.io/commits/gh-pages

**Comment by goern** [comment]
we are able to create a task for the aicoe-ci pipeline that would do the build and commit to the gh-pages branch...

/kind feature

**Comment by HumairAK** [comment]
We have an operate first bot being used for this, can be closed now. https://github.com/op1st
