### ISSUE TITLE
links to dashboards from https://www.operate-first.cloud/users/support/#moc-environment don't work

### ISSUE THREAD

**Issue by michaelfactor** [operate-first/operate-first.github.io-old#311]
In all cases unable to establish a connection.  
<img width="1053" alt="Screen Shot 2021-10-03 at 15 46 29" src="https://user-images.githubusercontent.com/18613732/135754360-18c45833-ea85-4c34-94ab-0e962f7ef7c6.png">

**Comment by schwesig** [comment]
change/update

Intro
- [ ] https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/r7WqgaBMk/operatefirst-availability?orgId=1&refresh=1m

Open Data Hub
- [x] https://www.operate-first.cloud/users/support/4 (see #297)
- [ ] https://odh.operate-first.cloud/

Kubeflow
- [x] https://www.operate-first.cloud/users/support/5 (see #297)
- [ ] http://istio-ingressgateway-istio-system.apps.zero.massopen.cloud/

ArgoCD
- [ ] https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/d/97AYZMTGk/argocd?orgId=1

Observatorium
- [ ] https://github.com/operate-first/support/blob/main/docs/add_service_monitoring.md
- [ ] http://thanos-query-frontend-opf-observatorium.apps.zero.massopen.cloud/
- [ ] https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/dashboards/f/VYns1DlGz/thanos

Cluster Logging Operator
- [ ] https://kibana-openshift-logging.apps.zero.massopen.cloud/
- [ ] https://elasticsearch-openshift-logging.apps.zero.massopen.cloud/

**Comment by schwesig** [comment]
parts of it in https://github.com/operate-first/operate-first.github.io/issues/297

**Comment by schwesig** [comment]
partly solved by https://github.com/operate-first/support/pull/426

**Comment by HumairAK** [comment]
links were updated, can be found here: https://github.com/operate-first/support/issues/298 
please create a new issue if there are any more broken links, thanks.
