### ISSUE TITLE
Blog post on basic interaction with prometheus metrics using the API

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#32]
Linked to AICoE/prometheus-api-client#164

**Comment by Shreyanand** [comment]
There is a blog from time series project on fetching the metrics using the api [here](https://www.operate-first.cloud/data-science/time-series/notebooks/ts-1-fetching-metrics.ipynb). @hemajv is there a more general purpose blog somewhere or is this good enough to close this issue?
