### ISSUE TITLE
Broken relative links after using back button

### ISSUE THREAD

**Issue by asmacdo** [operate-first/operate-first.github.io-old#331]
![Screenshot from 2021-11-18 12-02-34](https://user-images.githubusercontent.com/1028657/142462030-a6cf7443-baaa-48da-b796-bbd99832f9df.png)
The "blueprints" link leads to https://www.operate-first.cloud/blueprints/blueprint/ with a trailing slash.

The links on this page are under `blueprints/blueprint/adr/*` https://www.operate-first.cloud/blueprints/blueprint/adr/0000-use-markdown-architectural-decision-records.md

On Firefox and Chrome, if I click a link and hit back, the browser uses https://www.operate-first.cloud/blueprints/blueprint without the trailing slash.

The links on the same page are incorrect, leaving out `blueprint/` in the URL. https://www.operate-first.cloud/blueprints/adr/0000-use-markdown-architectural-decision-records.md

**Comment by TomasTomecek** [comment]
+1, still an issue I just ran into

**Comment by durandom** [comment]
we have a new website - no relevant anymore
