### ISSUE TITLE
Links on data-science-workflows page 

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/operate-first.github.io-old#344]
The links on the operate-first website for the [Data Science Workflow Page](https://www.operate-first.cloud/data-science/data-science-workflows/) seem broken. On further inspection, it seems that they are acting **flaky**. 
Once you may see this,
![image](https://user-images.githubusercontent.com/26301643/149151939-13f4feca-8505-4dfd-a35d-78cc0680d830.png)
But next time you may see this,
![image](https://user-images.githubusercontent.com/26301643/149152018-34ae4df0-74a6-459a-9116-ba805657b9e4.png)

**Comment by oindrillac** [comment]
It seems that when the page https://www.operate-first.cloud/data-science/data-science-workflows/ is navigated to from the website, it will have the trailing `/` and will result in the complete url and hence does not break. 

But when we directly open the link in a chrome browser, chrome seems to clip the trailing `/` at the end of `https://www.operate-first.cloud/data-science/data-science-workflows` which results in `data-science-workflows` not being appended to the url and results in an incomplete url like `https://www.operate-first.cloud/data-science/docs/setup_environment/JH_access.md`. 

I'm not certain if this is a fix, but I see gatsby allows us to configure trailing slashes on relative urls. Does setting this to `true` help? https://github.com/operate-first/operate-first.github.io/blob/master/gatsby-node.js#L26

**Comment by oindrillac** [comment]
btw we can observe the same issue with other pages on the site such as https://www.operate-first.cloud/data-science/ai4ci/
