### ISSUE TITLE
Broken link to all ADRs if navigated from the navigation menu - /docs/ should be /adr/ 

### ISSUE THREAD

**Issue by mykaul** [operate-first/operate-first.github.io-old#349]
Click - Blueprints and then try to go to Architecture Decision Records on the left navigation bar, and click on any ADR - seem broken.
For example, it leads to:
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0000-use-markdown-architectural-decision-records.md
instead of:
https://www.operate-first.cloud/blueprints/blueprint/adr/0000-use-markdown-architectural-decision-records.md

**Comment by mykaul** [comment]
Still relevant.

**Comment by durandom** [comment]
Yes, it's relevant and sorry for not updating the issue. 
We'll address the website by a relaunch soon. 
See https://github.com/operate-first/website-ng

**Comment by quaid** [comment]
> Yes, it's relevant and sorry for not updating the issue. We'll address the website by a relaunch soon. See https://github.com/operate-first/website-ng

Can you move all the still-relevant issues to the new repo? I don't seem to have the permissions (which is fine.)

**Comment by durandom** [comment]
ADRs are now linked from https://www.operate-first.cloud/community-cloud
