### ISSUE TITLE
Provide link to mailing list on community page

### ISSUE THREAD

**Issue by larsks** [operate-first/operate-first.github.io-old#350]
While there is a link to the mailing list on the [main page](https://www.operate-first.cloud/), it's somewhat hidden down at the bottom. The obvious place to find this would be on the [community page](https://www.operate-first.cloud/community/) page, but that only links to slack, twitter, and youtube.

**Comment by larsks** [comment]
While there is a link to the mailing list on the [main page](https://www.operate-first.cloud/), it's somewhat hidden down at the bottom. The obvious place to find this would be on the [community page](https://www.operate-first.cloud/community/) page, but that only links to slack, twitter, and youtube.

**Comment by HumairAK** [comment]
@larsks this can be closed now yes?
