### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ptrnull** [operate-first/operate-first.github.io-old#373]
Hello, the following links are broken:

https://www.operate-first.cloud/data-science/github-labeler/docs/contribute.md
https://www.operate-first.cloud/data-science/github-labeler/docs/content.md
https://www.operate-first.cloud/community-handbook/sre/incident-management/incident-management-procedure.md
https://www.operate-first.cloud/community-handbook/sre/incident-management/github-receiver-setup.md
https://www.operate-first.cloud/community-handbook/sre/incident-management/configure-prometheus-alerts.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0000-use-markdown-architectural-decision-records.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0001-use-gpl3-as-license.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0003-feature-selection-policy.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0004-argocd-apps-of-apps-structure.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0005-support-multi-environments-in-repos.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0006-monitoring-structure.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0007-alerting-setup.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0008-secrets-management.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0009-cluster-resources.md
https://www.operate-first.cloud/blueprints/blueprint/docs/adr/0010-common-auth-for-applications.md

**Comment by mykaul** [comment]
Dup of https://github.com/operate-first/operate-first.github.io/issues/349 ?

**Comment by durandom** [comment]
Hey thanks for the list ❤️ 
We're in the process of relaunching the website. See https://github.com/operate-first/website-ng
