### ISSUE TITLE
Find a suitable name for the "marketing" efforts wrt Operate First initiative

### ISSUE THREAD

**Issue by hemajv** [operate-first/operate-first.github.io-old#39]
what do you think about naming it something like `Community Support`?
@aakankshaduggal @oindrillac @durandom

**Comment by aakankshaduggal** [comment]
Sounds better :+1:

**Comment by durandom** [comment]
It's not just about support. The board should track all efforts that push the ODH operate first visibility forward. So "marketing" or "public relations /  PR" is more accurate. 

Let's just stick with it until we really get annoyed.
