### ISSUE TITLE
Add one open source data science blog post to this repo

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#5]
This should be the basis for proving this `post` -> `notebook render` -> `notebook deploy` workflow.

So maybe we can choose one where we already have a good notebook and jupyterhub image for

**Comment by oindrillac** [comment]
Discussed this with @shreyanand, we will start with the Categorical Encoding blog.
We have a blog ready [here](https://docs.google.com/document/d/1BQ9AGyZMMTt_r0tdgHrfs_1nD_CM8KxYA5aUfluhO1A/edit#).
@shreyanand, can we add this as a .md to this repo?

**Comment by oindrillac** [comment]
@durandom by around when do we want this blog to be ready? do you have a rough timeline?
