### ISSUE TITLE
move blogs into independent sub-directory

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#50]
Move blog to be published into an independent sub-directory in continuous-deployment repo and update readme instructions ([#38 comment](https://github.com/operate-first/operate-first.github.io/issues/38#issuecomment-713804474))

**Comment by hemajv** [comment]
so only the docs which are ready to be rendered on the website need to be placed in the `publish` sub-directory?

**Comment by oindrillac** [comment]
@hemajv yes. this is so that we do not include the unnecessary files during build
