### ISSUE TITLE
Render relative git urls in site

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#55]
Github relative links do not work for the Gatsby site.

In context to https://github.com/operate-first/operate-first.github.io/pull/53, there seems to be some issues in linking docs between multiple folders. The links seem to differ for the website and the GitHub repo. 

For instance, we have a doc here: https://hemajv.github.io/operate-first.github.io/cd-quicklab/odh-install-quicklab which contains a link `quicklab guide` and redirects to https://hemajv.github.io/operate-first.github.io/cd-quicklab/quicklab, however this link would be invalid in our GitHub repo doc (https://github.com/hemajv/continuous-deployment/blob/master/docs/installation_guides/quicklab/odh-install-quicklab.md) 

for the link to work in the website, we should update it in our .md as:
`[quicklab guide](./quicklab)`
however, this would result in a `404 Page Not Found error` when viewing within GitHub: https://github.com/hemajv/continuous-deployment/blob/master/docs/installation_guides/quicklab/quicklab

**Comment by cfchase** [comment]
As far as the relative part of this, you probably want to go one level up in the directory structure and that way you can use the same prefix.

As far as process .md files as links, you can customize the link generation https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/?=mdx or fork the plugin.  I think that might solve the relativity problem too by comparing the `.md` file absolute path and using the node.slug link.

**Comment by oindrillac** [comment]
@cfchase is this something you can look into?
