### ISSUE TITLE
Add an MOC page

### ISSUE THREAD

**Issue by hemajv** [operate-first/operate-first.github.io-old#59]
Add a new section on the nav bar to include on-boarding documents for users related to MOC such as logging into JupyterHub etc

**Comment by oindrillac** [comment]
- [x] Link on-boarding / getting access to cluster [doc](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/blob/master/docs/about-the-cluster.md#request-access-to-the-moc-cnv-cluster)
- [x] Create doc on how to access [JH](https://jupyterhub-opf-jupyterhub.apps.cnv.massopen.cloud/hub/login), link to the doc in the `odh-moc-support` repo
