### ISSUE TITLE
add more information to gh-pages push

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#6]
Can we configure the gh-pages plugin to include more information in the push to the gh-pages branch?

https://github.com/operate-first/operate-first.github.io/commits/gh-pages

E.g. adding the PR that resulted in the change?

Not super important, if it's not straightforward to implement

**Comment by tumido** [comment]
Should be pretty easy to do. :) You can choose your desired message from these variables: https://docs.travis-ci.com/user/environment-variables/ (btw, this is not a PR build, but rather a push build, so pull request specific variables are not available)

My take: https://github.com/operate-first/operate-first.github.io/pull/12
