### ISSUE TITLE
Removing placeholder Jupyter Notebook throws a compile error

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#75]
As I am trying to build the site after removing the placeholder Jupyter Notebook in [section](https://operate-first.github.io/getting-started/jupyter-notebooks), I get a compile error as follows
See changes in my [fork](https://github.com/oindrillac/operate-first.github.io)

```
Failed to compile
There was an error in your GraphQL query:

Cannot query field "allJupyterNotebook" on type "Query".

If you don't expect "allJupyterNotebook" to exist on the type "Query" it is most likely a typo.
However, if you expect "allJupyterNotebook" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allJupyterNotebook" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /home/ochatter/Workspace/github/operate-first/operate-first.github.io/src/components/JupyterNotebook/JupyterNotebook.js

./src/components/JupyterNotebook/JupyterNotebook.js
Module Error (from ./node_modules/eslint-loader/index.js):

/home/ochatter/Workspace/github/operate-first/operate-first.github.io/src/components/JupyterNotebook/JupyterNotebook.js
  10:9  error  Cannot query field "allJupyterNotebook" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)
```
@cfchase can you please help me understand this?

**Comment by cfchase** [comment]
So by deleting all the Jupyter notebooks, unfortunately that query isn't just returning an empty set, it's no longer valid because Gatsby can't infer a schema from nothing.  The easiest thing you can do is the 3rd recommendation

> - You want to optionally use your field "allJupyterNotebook" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. **A quick fix is to add at least one entry with that field ("dummy content")**

I would just leave the `hello-world.ipynb` somewhere in the content directory.  You don't need to use it or save any of the markdown or link to anything.

**Comment by oindrillac** [comment]
thanks for the explanation @cfchase. Keeping the hello-world.ipynb in one of the directories helped and solved the error.
