### ISSUE TITLE
Rendering blogs so that they look pretty

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/operate-first.github.io-old#86]
As a user of the operate first website I would like the blogs to look pretty. Here are some suggestions to do that:

1. Have a main image for every blog that would be the first thing that the user sees. 
2. Also, use that image as a thumbnail in the project overview page.
3. Define guidelines for front matter required for each blog. For example: Author(s), tags, category, date updated, description, main image

4. Update how tags are rendered in the blog to make it more appealing.
5. Place blogs in the center of the page with limited width instead of rendering them on a full page.

**Comment by oindrillac** [comment]
related issue #18
