### ISSUE TITLE
ADR do not render

### ISSUE THREAD

**Issue by goern** [operate-first/operate-first.github.io-old#88]
https://operate-first.github.io/blueprint/docs/adr/0000-use-markdown-architectural-decision-records does not render, even though I tested it locally with the dev.sh script...

/assign @oindrillac
/assign @cfchase  
/kind bug

**Comment by oindrillac** [comment]
the `content-sources.yaml` was configured to fetch content from `dir: blueprint/docs/adr`, hence while referencing the documents, we can directly reference them using the set `urlPrefix` as `/blueprint/0000-use-markdown-architectural-decision-records` ie. no need to repeat `/docs/adr`

**Comment by goern** [comment]
uh, got it!
