### ISSUE TITLE
Rearrange items on left hand toc

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#93]
Is there a way to rearrange items on the left hand toc? ie move items from the main toc(toc.yaml) below other items from external toc.

It would be nice to have items like `Resources` go at the bottom of the toc below the other items acquired from external/remote toc items ie below "AI for Continuous Integration".

![image](https://user-images.githubusercontent.com/32435206/99068303-43e12b00-257a-11eb-9923-aa6d9039a460.png)

@cfchase do you have a recommendation on if/how we can achieve this?

Do we need to move those items out of the main toc in that case?

**Comment by cfchase** [comment]
It just goes in the order you load the `toc.yaml` files from`toc-sources.yaml`.  If there's a `resource-toc.yaml` with your menu item at the bottom of `toc-sources.yaml`, it should show up at the bottom.

**Comment by oindrillac** [comment]
Got it. Will move the items which need to be rearranged into a separate toc.yaml. Thanks @cfchase
