### ISSUE TITLE
Get links to sections on toc

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#94]
Is there a way we can get urls to high level section items on toc panel eg "MOC - ODH Users", "Data Science Projects" , "Architectural Decision Records" etc?

Having links to sections would be useful since, then `Getting Started` can also have links to the respective sections, with a small sentence about what its about for first time users.

(please see discussion on anchor links to sections [here](https://github.com/operate-first/operate-first.github.io/issues/52#issuecomment-717280969).

**Comment by cfchase** [comment]
The Patternfly nav doesn't support this because clicking on the link of a group isn't a navigation element, it opens the sub-menu.  Seems like it would be confusing from a UI perspective to try and do both on a click.  It might be worth it to make an intro page as the first section and that's where you could put your sections (with links) and the descriptions.

**Comment by oindrillac** [comment]
> be worth it to make an intro page as the first section and that's where you could put your sections (with links) and the descriptions

@cfchase I see. So for the the "intro page as the first section and that's where you could put your sections (with links) " - by ` with links`, you mean the individual document links correct? - since we cannot get the links to the section itself? 

So for eg: are you suggesting something like ?

## Data Science Projects
This section consists of examples of data science projects at Red Hat.
* [Projects Overview](http://www.operate-first.cloud/data-science-projects/projects-overview) - A high-level overview of all data science projects at AICoE Red Hat.
* [Categorical Encoding](http://www.operate-first.cloud/advanced-topics/categorical-encoding/blog) - A blog on encoding schemes for nominal categorical variables

**Comment by oindrillac** [comment]
With changes in #117 - adding Top Navigation lets us achieve the purpose of 3 level nav and get links to respective sections .
