### ISSUE TITLE
Low-Fi wireframe for landing page

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#95]
Attaching mockups of low-fi wireframe sketches for the home page of the site.

Feel free to add suggestions/comments

**Comment by oindrillac** [comment]
![Op1st wireframe (1)](https://user-images.githubusercontent.com/32435206/99097850-2f1a8c80-25a6-11eb-9a0b-0b5983403873.png)

**Comment by oindrillac** [comment]
![Op1st wireframe (2)](https://user-images.githubusercontent.com/32435206/99098218-b49e3c80-25a6-11eb-903e-66b82042c206.png)

**Comment by oindrillac** [comment]
![Uploading Op1st wireframe (3).png…]()

**Comment by oindrillac** [comment]
![Uploading Op1st wireframe (4).png…]()

**Comment by oindrillac** [comment]
![Op1st wireframe (3)](https://user-images.githubusercontent.com/32435206/99098502-11015c00-25a7-11eb-96d3-438406dc5a13.png)

**Comment by oindrillac** [comment]
![Op1st wireframe (4)](https://user-images.githubusercontent.com/32435206/99098541-1e1e4b00-25a7-11eb-89a2-84e7c6299232.png)

**Comment by oindrillac** [comment]
Illustrations are sourced from https://undraw.co/

**Comment by hemajv** [comment]
I think these look great! :smiley:

**Comment by aakankshaduggal** [comment]
Looks great @oindrillac :+1:

**Comment by SankBad** [comment]
It looks great :heart_eyes: 
Can we add those square boxes for data science projects also. Because, as the number of projects will increase dropdown will be really long.

**Comment by SankBad** [comment]
Something like we discuss over here: [doc](https://docs.google.com/document/d/1jV687x0bflKUOTIgixDK8ehlOM8wgfbJr_VGQlBLZjM/edit)

**Comment by tumido** [comment]
> Illustrations are sourced from https://undraw.co/

@oindrillac you can also use https://2.flexiple.com/scale/all-illustrations which I've recently discovered. (just adding it to your collection of CC/Opensource illustration sites. :slightly_smiling_face: )  They are a bit different than undraw... I personally like undraw better, but that's just matter of taste.
