### ISSUE TITLE
Add arbitrary content

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#98]
IIUC we can only add content by explicitly adding a page to https://github.com/operate-first/operate-first.github.io/blob/master/content/toc.yaml

How about pages that don't show up in the Navbar? 
Can we have a folder and get everything in that folder added as resolvable pages to the site?

Maybe that's related to #97 ?

**Comment by cfchase** [comment]
`toc.yaml` files are just the data for the left hand nav.  Pages (markdown docs or pages) are available whether or not they appear on the nav, so they should be there.

**Comment by durandom** [comment]
Works indeed. Somehow it didnt when I tried first. Thanks
